<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1544707962159" stop="1544708003113">
  <name>test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1544707962159" status="passed" stop="1544707972436">
      <name>TestLogin.test_login[13013013010-123123-88880]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4140-MainThread"/>
        <label name="host" value="DESKTOP-KV841JB"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1544707972437" status="failed" stop="1544707982951">
      <name>TestLogin.test_login[13013013010-123123-88881]</name>
      <failure>
        <message>TimeoutException: Message: 
</message>
        <stack-trace>self = &lt;test_login.TestLogin object at 0x00000039275B4D30&gt;, username = '13013013010', password = '123123', number = '8888'

    @pytest.mark.parametrize("username, password, number", get_data())
    def test_login(self, username, password, number):
&gt;       self.login.page_click_login_a()

scripts\test_login.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
page\page_login.py:8: in page_click_login_a
    self.base_click_element(page.login_a)
base\base.py:13: in base_click_element
    self.base_find_element(loc).click()
base\base.py:10: in base_find_element
    return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*loc))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;selenium.webdriver.support.wait.WebDriverWait (session="f528573ef27072644c764fd9aa029921")&gt;
method = &lt;function Base.base_find_element.&lt;locals&gt;.&lt;lambda&gt; at 0x00000039275B6378&gt;, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() &gt; end_time:
                break
&gt;       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

e:\pythonjsq\lib\site-packages\selenium\webdriver\support\wait.py:80: TimeoutException</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4140-MainThread"/>
        <label name="host" value="DESKTOP-KV841JB"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1544707982951" status="failed" stop="1544707993057">
      <name>TestLogin.test_login[13013013010-123123-88882]</name>
      <failure>
        <message>TimeoutException: Message: 
</message>
        <stack-trace>self = &lt;test_login.TestLogin object at 0x0000003927601390&gt;, username = '13013013010', password = '123123', number = '8888'

    @pytest.mark.parametrize("username, password, number", get_data())
    def test_login(self, username, password, number):
&gt;       self.login.page_click_login_a()

scripts\test_login.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
page\page_login.py:8: in page_click_login_a
    self.base_click_element(page.login_a)
base\base.py:13: in base_click_element
    self.base_find_element(loc).click()
base\base.py:10: in base_find_element
    return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*loc))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;selenium.webdriver.support.wait.WebDriverWait (session="f528573ef27072644c764fd9aa029921")&gt;
method = &lt;function Base.base_find_element.&lt;locals&gt;.&lt;lambda&gt; at 0x00000039275E3840&gt;, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() &gt; end_time:
                break
&gt;       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

e:\pythonjsq\lib\site-packages\selenium\webdriver\support\wait.py:80: TimeoutException</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4140-MainThread"/>
        <label name="host" value="DESKTOP-KV841JB"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1544707993058" status="failed" stop="1544708003113">
      <name>TestLogin.test_login[13013013010-123123-88883]</name>
      <failure>
        <message>TimeoutException: Message: 
</message>
        <stack-trace>self = &lt;test_login.TestLogin object at 0x000000392760B8D0&gt;, username = '13013013010', password = '123123', number = '8888'

    @pytest.mark.parametrize("username, password, number", get_data())
    def test_login(self, username, password, number):
&gt;       self.login.page_click_login_a()

scripts\test_login.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
page\page_login.py:8: in page_click_login_a
    self.base_click_element(page.login_a)
base\base.py:13: in base_click_element
    self.base_find_element(loc).click()
base\base.py:10: in base_find_element
    return WebDriverWait(self.driver, timeout, poll).until(lambda x: x.find_element(*loc))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;selenium.webdriver.support.wait.WebDriverWait (session="f528573ef27072644c764fd9aa029921")&gt;
method = &lt;function Base.base_find_element.&lt;locals&gt;.&lt;lambda&gt; at 0x00000039275E3A60&gt;, message = ''

    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
            return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() &gt; end_time:
                break
&gt;       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

e:\pythonjsq\lib\site-packages\selenium\webdriver\support\wait.py:80: TimeoutException</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="4140-MainThread"/>
        <label name="host" value="DESKTOP-KV841JB"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
